# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6016fa2dec1fc442c1903dfacf7cb8023546562218213697fa3883f01d2162faba49f8a587e7aecaa03f4c93f9ef13cb63a191f8a30cbd06ad4a2227dfa74542

test:
  secret_key_base: 934c5971df649cfbbcbf6cc48decc65445527b58da0e6e6bd8789d3fbbd19a3a51d7aed2bfc9b40d26d0ace86e0d05a7e5c7371eadbe796aa87eff2fea738bb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
